---
title: "Exercise: Tuning the Model"
output: html_document
---

# Introduction

Model tuning is the process of simplifying a model
while preserving or improving predictive
performance.

# Case Study

```{r}
library(tidyverse)
county_corn_data = read.csv("data/county_environments.csv")

ia_and_il_corn = county_corn_data %>%
  filter(state %in% c("IL", "IA"))

ia_and_illinois_model = lm(corn ~ ppt + whc + sand + silt + clay + om, data = ia_and_il_corn)
```

```{r}
variables_of_interest = ia_and_il_corn %>%
  select(ppt, whc, sand, silt, clay, om)
```

```{r}
library(psych)
partial.r(variables_of_interest)
```

## Baseline Cross-Validation

```{r}
library(caret)

set.seed(123)
train.control <- trainControl(method = "repeatedcv",
                              number = 10, repeats = 3)
model <- train(corn ~ ppt + whc + sand + silt + clay + om,
               data=ia_and_il_corn,
               method = "lm",
               trControl = train.control)
print(model)
```

## Drop Sand

```{r}
model_wo_sand = lm(corn ~ ppt + whc + silt + clay + om, data = ia_and_il_corn)
```

```{r}
library(broom)

tidy(model_wo_sand)
```

```{r}
glance(model_wo_sand)
```

```{r}
set.seed(123)
train.control <- trainControl(method = "repeatedcv",
                              number = 10, repeats = 3)
model <- train(corn ~ ppt + whc + silt + clay + om,
               data=ia_and_il_corn,
               method = "lm",
               trControl = train.control)
print(model)
```

## Drop Sand and Silt

```{r}
model_wo_sand_silt = lm(corn ~ ppt + whc + clay + om, data = ia_and_il_corn)
```

```{r}
tidy(model_wo_sand_silt)
```

```{r}
glance(model_wo_sand_silt)
```

```{r}
set.seed(123)
train.control <- trainControl(method = "repeatedcv",
                              number = 10, repeats = 3)
model <- train(corn ~ ppt + whc + clay + om,
               data=ia_and_il_corn,
               method = "lm",
               trControl = train.control)
print(model)
```

# Practice

```{r}
thompson_corn = read.csv("data/thompson_corn.csv")

thompsom_model = lm(yield ~ rain6 + rain7 + temp6 + temp7, thompson_corn)
```

```{r}
tidy(thompsom_model)
```

```{r}
glance(thompsom_model)
```

```{r}
library(caret)

set.seed(123)
train.control <- trainControl(method = "repeatedcv",
                              number = 10, repeats = 3)
model <- train(yield ~ rain6 + rain7 + temp6 + temp7,
               data=thompson_corn,
               method = "lm",
               trControl = train.control)
print(model)
```

Create a reduced model by removing `temp6`.

```{r}
thompsom_model_wo_temp6 = lm(yield ~ rain6 + rain7 + temp7, thompson_corn)
```

```{r}
tidy(thompsom_model_wo_temp6)
```

```{r}
glance(thompsom_model_wo_temp6)
```

```{r}
library(caret)

set.seed(123)
train.control <- trainControl(method = "repeatedcv",
                              number = 10, repeats = 3)
model <- train(yield ~ rain6 + rain7 + temp7,
               data=thompson_corn,
               method = "lm",
               trControl = train.control)
print(model)
```
