---
title: "Exercise: SSURGO"
output: html_document
---

# Introduction

This optional exercise demonstrates how to pull and
map SSURGO soil information for a field boundary in
R.

# Load Field Data

```{r}
library(sf)
library(tidyverse)
library(leaflet)

field = st_read("data/yield shape.shp")
```

## Build Initial Yield Map

```{r}
palette_yield = colorBin("RdYlGn", field$Yld_Vol_Dr)

field %>%
  leaflet() %>%
  addCircleMarkers(
    fillColor = ~palette_yield(Yld_Vol_Dr),
    fillOpacity = 0.8,
    weight = 0,
    radius=0.1
  ) %>%
  addProviderTiles(provider = providers$Esri.WorldImagery) %>%
  addLegend(values = ~Yld_Vol_Dr,
            pal = palette_yield)
```

## Pull SSURGO Data

```{r}
library(FedData)
library(sp)
soil_data_sp = as(field, "Spatial")
soil_map = get_ssurgo(soil_data_sp, "example")
soil_sf = st_as_sf(soil_map$spatial) %>%
  st_set_crs(4326)

mu_point = soil_map$tabular$mapunit %>%
  dplyr::select(musym, muname, mukey)

horizon_diagnostics = soil_map$tabular$chorizon %>%
  select(hzname, sandtotal.r, silttotal.r, claytotal.r, om.r, awc.r, ksat.r, cec7.r, cokey, chkey)

texture = soil_map$tabular$chtexturegrp %>%
  filter(rvindicator=="Yes") %>%
  select(texdesc, chkey)

slope = soil_map$tabular$component %>%
  select(drainagecl, slope.r, mukey, cokey)

parent_material = soil_map$tabular$copm %>%
  filter(pmorder==1 | is.na(pmorder)) %>%
  select(pmkind, copmgrpkey, copmkey)

pm_group = soil_map$tabular$copmgrp %>%
  select(cokey, copmgrpkey)

component = soil_map$tabular$component %>%
  select(mukey, cokey)

all_soil_data = mu_point %>%
  left_join(component) %>%
  left_join(horizon_diagnostics) %>%
  group_by(mukey) %>%
  filter(chkey==min(chkey)) %>%
  ungroup() %>%
  left_join(texture) %>%
  left_join(slope) %>%
  left_join(pm_group) %>%
  left_join(parent_material) %>%
  select(-c(copmgrpkey, copmkey, musym, cokey))

complete_soil_data = soil_sf %>%
  rename_all(tolower) %>%
  mutate(mukey = as.numeric(mukey)) %>%
  left_join(all_soil_data)
```

## Example Map of SSURGO Variable

```{r}
library(grDevices)
pal_om = colorNumeric("RdYlGn", complete_soil_data$om.r)

complete_soil_data %>%
  leaflet() %>%
  addProviderTiles(provider = providers$Esri.WorldImagery) %>%
  addCircleMarkers(
    radius = 4,
    weight=0,
    fillColor = ~ pal_om(om.r),
    opacity = 0.8,
    popup = as.character(complete_soil_data$om.r)
  )
```

# Notes

Useful variables in `complete_soil_data` include:

- `sandtotal.r`
- `silttotal.r`
- `claytotal.r`
- `om.r`
- `awc.r`
- `ksat.r`
- `cec7.r`
- `texdesc`
- `drainagecl`
- `slope.r`
